### PR TITLE
Ls 1

### PR DESCRIPTION
**Pull request by StanislavDmytriyev**
**No pain no gain.**
Finished implementing corrections as per your instructions.
Slider buttons added Frankensteins. Ready-to-use CSS saved for those and tested (don't have any experience yet with theese).

### CODE REVIEW

**Comment by savenkovao** [comment]
image
Since dots are slider controls also, consider using buttons, please

**Comment by savenkovao** [comment]
Missing slider controls
image

**Comment by savenkovao** [comment]
image
Since numbers are slider controls also, consider using buttons, please

**Comment by savenkovao** [comment]
Looks like nav also
image

**Comment by StanislavDmytriyev** [comment]
@savenkovao , it seems like all observations were corrected. 
Kindly take a look.

**Comment by StanislavDmytriyev** [comment]
@savenkovao , it seems like all observations were corrected.
Kindly take a look.
*I hope I know what I'm doing and this is just one more merge request.

**Comment by savenkovao** [comment]
Still problems with sprite
Consider fixing in next PR, please
image

**Pull request merged**
