### PR TITLE
Ls 2

### PR DESCRIPTION
**Pull request by StanislavDmytriyev**
Feeling somewhat excited and axhausted at the same time. 
@savenkovao , kindly check my PR. 
That was quite an experience!

### CODE REVIEW

**Comment by savenkovao** [comment]
Consider moving text into the <a> 
image

**Comment by savenkovao** [comment]
Consider adding hover/active effects for all links in project, please.
Choose your own styles, if there is no in figma

image

**Comment by savenkovao** [comment]
I guess these cards should also be links.
Consider adding hover effects on your preference, please
image

**Comment by savenkovao** [comment]
Consider adding hover effects, please
image

**Comment by savenkovao** [comment]
these div is junk from the semantics/indexing perspective. Consider using pseudoelement for it
image

**Comment by savenkovao** [comment]
In semantics layout, we should strive for a minimum of junk elements. So, everything, that might be done CSS-only (without HTML), should be done with CSS only.

E.g. 
green figures might be exported as a single picture & set as a background for the block.
image
image

The blue box might be pseudoelement

**Comment by savenkovao** [comment]
Block title is saying, that those items are links
image

**Comment by savenkovao** [comment]
I see text-shadow on most texts. Is it done by purpose?
image

**Comment by savenkovao** [comment]
Also pseudoelements
image
image

**Comment by savenkovao** [comment]
Wrong font-weight
image

**Comment by savenkovao** [comment]
Consider addin hovver effect (e.g. opacity, scaling etc)

image

**Comment by savenkovao** [comment]
Weird hover effect on the logo, in my opinion. Does not look friendly, try some lighter effect

image

**Comment by savenkovao** [comment]
These cards are also links (let's imagine, that after clicking user should go to a specific course page)

image

**Comment by savenkovao** [comment]
Consider using new image, please
image

**Comment by StanislavDmytriyev** [comment]
> Weird hover effect on the logo, in my opinion. Does not look friendly, try some lighter effect
> 
> image

This is what we have in Figma, just a black logo on hover.

**Comment by StanislavDmytriyev** [comment]
What a lovely Saturday evening. Or is it Sunday morning already? :)

**Comment by StanislavDmytriyev** [comment]
What a lovely Saturday evening. Or is it Sunday morning already? :)
Guess, all observations were rectified. 
Learned a tonn of new stuff tonight. 
TY

**Comment by savenkovao** [comment]
Consider using a separate standalone class for titles & blu lines, instead of duplicating styles for each block

image

**Comment by savenkovao** [comment]
Consider using blockquote here since it's a quote
image
image

**Comment by savenkovao** [comment]
I believe, all button classes have a lot in common. I suggest moving common styles into common class & leave all more specific in blue/green-button classes (only that is different)

So, you can configure your button by a set of classes. Of course, the common button class should be also ready-to-use (have enough styles to display a button, e.g. with gray bg).
Also, imagine the case, in which you need to change border-radius  (or other common property) for all buttons. ATM you need to go over all of them, instead of changing a single place.

image


Check out Alex's solution
https://github.com/Activine/hyz_academy/pull/3

**Comment by savenkovao** [comment]
A small white line is visible out ob blue border (not according to design)
image

Consider providing styles for :focus events, instead of focus-visible, as it covers more interaction cases (including js-interaction)
image

**Pull request merged**
