### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by StanislavDmytriyev**
Finished HW ls_1 the way I see it with my unexperienced eye.

### CODE REVIEW

**Comment by savenkovao** [comment]
Consider implementing this line css-only. No need of using image here
image

**Comment by savenkovao** [comment]
Consider adding a container for starts. I believe it will be helpful later on.
I also recommend using svg directly in order to implement ratings like 4.23. Check out existing solutions
image
image

**Comment by savenkovao** [comment]
Interesting solution. Could you tell what is the reason for doing this, please?
image

**Comment by savenkovao** [comment]
I guess, the list is not required here. wdyt?

Creating layout (writing code) we'd rather add just as much as needed in order to avoid excessive structures etc.

image

**Comment by savenkovao** [comment]
Does this line have any semantic meaning to add in HTML (to be indexed later on)?
I believe, it can be implemented using CSS

image

**Comment by savenkovao** [comment]
These elements are clickable controls of the slider. Consider using the button here. 
Besides, the exported image here should be only an arrow.

But if we think about future performance, we'd rather use only one image twice (just transform it with CSS later)
The fastest solution here might be a CSS-only solution or using SVG directly in code in order to avoid external calls (fetching images)

image

**Comment by savenkovao** [comment]
Also ccs-only solution suggestions.
The play button should be a button, isn't it?
image

**Comment by savenkovao** [comment]
Non-content images. I tend to use ccs-only or SVG-direct solutions. WDYT?
image

**Comment by savenkovao** [comment]
What is the semantic reason to use aside here?

Also CSS-only solution suggestion (as non-content images)

image

**Comment by savenkovao** [comment]
I tend to CSS-only, SVG-direct or sprite solution with icons
image

**Comment by savenkovao** [comment]
Consider using as css-background

image

**Comment by savenkovao** [comment]
Since this are slider controls consider using button 
image

**Comment by savenkovao** [comment]
Consider refactoring footer & nav blocks, please
image
image

**Comment by savenkovao** [comment]
Everything else is good!

I like the way you organize your code

**Comment by StanislavDmytriyev** [comment]
> Consider implementing this line css-only. No need of using image here image

Done.

**Comment by StanislavDmytriyev** [comment]
> Consider adding a container for starts. I believe it will be helpful later on. I also recommend using svg directly in order to implement ratings like 4.23. Check out existing solutions image image

Done.

**Comment by StanislavDmytriyev** [comment]
> I guess, the list is not required here. wdyt?
> 
> Creating layout (writing code) we'd rather add just as much as needed in order to avoid excessive structures etc.
> 
> image

Agreed to leave the UL.

**Comment by StanislavDmytriyev** [comment]
> Does this line have any semantic meaning to add in HTML (to be indexed later on)? I believe, it can be implemented using CSS
> 
> image

Removed.

**Comment by StanislavDmytriyev** [comment]
> Non-content images. I tend to use ccs-only or SVG-direct solutions. WDYT? image

Re-coded using sprite.svg

**Comment by StanislavDmytriyev** [comment]
> These elements are clickable controls of the slider. Consider using the button here. Besides, the exported image here should be only an arrow.
> 
> But if we think about future performance, we'd rather use only one image twice (just transform it with CSS later) The fastest solution here might be a CSS-only solution or using SVG directly in code in order to avoid external calls (fetching images)
> 
> image

Made a Frankenstein. 
Inserted as 1st and last <li> of concerned <ul>. Found a working script for these. Will position them with CSS when the time is right.
`
  <a class="prev" onclick="plusSlides(-1)">❮</a>
      <a class="next" onclick="plusSlides(1)">❯</a>`

**Comment by savenkovao** [comment]
Slider dots controls are missing
image

**Pull request closed without merging**
